export const ROUTES = {
  home: '/',
  authMax: '/auth/max',
  reportNew: '/report/new',
  myReports: '/reports',
  incident: (incidentId: string) => `/incidents/${incidentId}`,
  incidentResolution: (incidentId: string) => `/incidents/${incidentId}/resolution`,
  myHouse: '/house',
  news: '/news',
  newsItem: (newsId: string) => `/news/${newsId}`,
  notifications: '/notifications',
  profile: '/profile',
  selectHouse: '/profile/house',
  settings: '/settings',
  help: '/help',
} as const;
