export const ROUTES = {
  login: '/login',
  home: '/',
  organizations: '/organizations',
  organization: (organizationId: string) => `/organizations/${organizationId}`,
  houses: '/houses',
  messages: '/messages',
  staff: '/staff',
  residents: '/residents',
  resident: (residentId: string) => `/residents/${residentId}`,
  reports: '/reports',
  report: (reportId: string) => `/reports/${reportId}`,
  incidents: '/incidents',
  incident: (incidentId: string) => `/incidents/${incidentId}`,
  news: '/news',
  profile: '/profile',
} as const;
