add_header Content-Security-Policy-Report-Only "default-src 'self'; script-src 'self' https://st.max.ru; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https://i.oneme.ru https://*.oneme.ru; font-src 'self' data:; connect-src 'self' https://st.max.ru; object-src 'none'; base-uri 'self'; form-action 'self'" always;
add_header X-Content-Type-Options "nosniff" always;
add_header Referrer-Policy "no-referrer" always;
add_header Permissions-Policy "camera=(self), microphone=(), geolocation=(self), payment=(), usb=()" always;
add_header Strict-Transport-Security "max-age=31536000" always;
